name: test

# Test the Python client library

on:
  push:
    branches: [main, dev]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    name: build - Python ${{ matrix.python-version }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      # Python setup
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        run: |
          python -m pip install --upgrade pip setuptools wheel
          scripts/build.sh

      # Run tests
      - name: Run tests in release mode
        if: ${{ github.ref == 'refs/heads/main' }}
        run: scripts/test.sh --release
      - name: Run tests
        if: ${{ github.ref != 'refs/heads/main' }}
        run: scripts/test.sh
